### ISSUE TITLE
Storj IPFS plugin

### ISSUE THREAD

**Issue by cupOJoseph** [storj/ipfs-demo#10]
Goal: create a plugin for IPFS on the server which runs the Storj configuration. Allow for a storj configuration profile during `ipfs init`. 

## Resources
- example ipfs plugin https://github.com/ipfs/go-ipfs-example-plugin
- example storj + ipfs plugin integration: https://github.com/RTradeLtd/storj-ipfs-ds-plugin/tree/master/fsrepo This is what we're going for, using storj config, but a cleaner solution with some explanation docs would be good.
- storj cmd tool could be useful https://github.com/storj/storj/tree/master/cmd/uplink

## Acceptance Criteria
Add a basic IPFS plugin to the project. The plugin can run with a storj configuration
Please include some docs on how this works.

**Comment by kaloyan-raev** [comment]
We have no such a plugin implemented at https://github.com/storj/ipfs-go-ds-storj
